import type { Metadata } from "next";
import type { AppProps } from "next/app";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { CssBaseline } from "@mui/material";
import '../styles/globals.css'; // If you're using a global stylesheet
import { ThemeModeProvider } from "../context/ThemeContext";


export const metadata: Metadata = {
  title: "Uzuri Creative Ltd",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeModeProvider>
      <QueryClientProvider client={queryClient}>
        <CssBaseline />
        <Component {...pageProps} />
      </QueryClientProvider>
    </ThemeModeProvider>
  );
}